"""Ajout du champ last_security_training au modèle User

Revision ID: 6de55fe79c1b
Revises: 34406661e0f1
Create Date: 2025-06-01 19:14:52.105022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de55fe79c1b'
down_revision: Union[str, None] = '34406661e0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajout du champ last_security_training à la table user
    op.add_column('user', sa.Column('last_security_training', sa.DateTime(), nullable=True, comment="Date de la dernière formation de sécurité suivie"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_security_training')
    # ### end Alembic commands ###
